---
name: Static analysis

"on":
  pull_request: {}

permissions: {}

jobs:
  pre_commit_checks:
    name: pre-commit checks
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install tool dependencies
        uses: jdx/mise-action@v2

      - name: Run pre-commit
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
