---
name: Validate Changes to Workflow

"on":
  pull_request: {}

permissions: {}

jobs:
  validate_changes:
    name: validate action changes
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read
      # required to read from the PR
      pull-requests: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: updatecli-minor-apply
        uses: prefecthq/actions-updatecli-apply@${{ github.head_ref }}
        with:
          manifest-path: .github/updatecli/manifest.yaml
          run-type: minor
